# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    # -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
# -   repo: https://github.com/pycqa/isort
#     rev: 5.11.2
#     hooks:
#       - id: isort
#         name: isort (python)
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8.10
# -   repo: local
#     hooks:
#     -   id: pylint
#         name: pylint
#         language: system
#         entry: pylint
#         types: [python]
#         args:  [
#             "-rn", # Only display messages
#             "-sn", # Don't display the score
#             "--recursive=y"
#         ]
# -   repo: local
#     hooks:
#     -   id: pytest-check
#         name: pytest-check
#         entry: pytest
#         language: system
#         pass_filenames: false
#         always_run: true
#         args: [
#             "tests/"
#         ]
