channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=20.0.2
- pip:
  - mlflow==2.4
  - numpy==1.24.3
  - pandas==2.0.2
  - psutil==5.9.5
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - typing-extensions==4.6.3
  - xgboost==1.7.5
name: mlflow-env
