from typing import Dict, Text

# DATABASE_URI: Text = "postgresql://admin:admin@localhost:5432/monitoring_db"
DATA_COLUMNS: Dict = {
    "target_col": "Price",
    "prediction_col": "predictions",
    "num_features": [
        "Mileage",
        "Power",
        "Offer_from_Osoby_prywatnej",
        "Vehicle_brand_Infiniti",
        "Vehicle_brand_Lexus",
        "Vehicle_brand_Jaguar",
        "Vehicle_brand_Maserati",
        "Vehicle_brand_Jeep",
        "Vehicle_brand_Kia",
        "Vehicle_brand_Hyundai",
        "Vehicle_brand_Honda",
        "Vehicle_brand_Lamborghini",
        "Vehicle_brand_Land_Rover",
        "Vehicle_brand_Mercedes-Benz",
        "Vehicle_brand_Mazda",
        "Vehicle_brand_Peugeot",
        "Vehicle_brand_MINI",
        "Vehicle_brand_Opel",
        "Vehicle_brand_Polonez",
        "Vehicle_brand_Porsche",
        "Vehicle_brand_Nissan",
        "Vehicle_brand_Tarpan",
        "Vehicle_brand_SsangYong",
        "Vehicle_brand_Seat",
        "Vehicle_brand_Renault",
        "Vehicle_brand_Tesla",
        "Vehicle_brand_Suzuki",
        "Vehicle_brand_Skoda",
        "Vehicle_brand_Toyota",
        "Vehicle_brand_Subaru",
        "Vehicle_brand_Volkswagen",
        "Vehicle_brand_Volvo",
        "Vehicle_brand_DS_Automobiles",
        "Vehicle_brand_Inny",
        "Year_of_production_2016",
        "Year_of_production_2012",
        "Year_of_production_2020",
        "Year_of_production_2019",
        "Year_of_production_2017",
        "Year_of_production_2014",
        "Year_of_production_2013",
        "Year_of_production_2005",
        "Year_of_production_2000",
        "Year_of_production_2002",
        "Year_of_production_2018",
        "Year_of_production_2009",
        "Year_of_production_2006",
        "Year_of_production_2004",
        "Year_of_production_2011",
        "Year_of_production_1992",
        "Year_of_production_2022",
        "Year_of_production_2008",
        "Year_of_production_1999",
        "Year_of_production_1994",
        "Year_of_production_2007",
        "Year_of_production_2023",
        "Year_of_production_2021",
        "Year_of_production_2015",
        "Year_of_production_1998",
        "Year_of_production_2001",
        "Year_of_production_2010",
        "Year_of_production_2003",
        "Year_of_production_1997",
        "Year_of_production_1996",
        "Year_of_production_1983",
        "Fuel_type_Benzyna",
        "Fuel_type_Benzyna+LPG",
        "Fuel_type_Diesel",
        "Fuel_type_Elektryczny",
        "Fuel_type_Hybryda",
        "Gearbox_Manualna",
        "Body_type_Kabriolet",
        "Body_type_SUV",
        "Body_type_Sedan",
        "Body_type_Coupe",
        "Body_type_Minivan",
        "Body_type_Kompakt",
        "Body_type_Auta_miejskie",
        "Body_type_Kombi",
        "Number_of_doors_3",
        "Number_of_doors_5",
        "Number_of_doors_4",
        "Number_of_doors_2"
    ],
}
DATA_COLUMNS["columns"] = (
    DATA_COLUMNS["num_features"] +
    [DATA_COLUMNS["target_col"], DATA_COLUMNS["prediction_col"]]
)
